use anyhow::Result;

use crate::models::{ComplianceReport, Severity};

pub fn to_json(report: &ComplianceReport) -> Result<String> {
    Ok(serde_json::to_string_pretty(report)?)
}

pub fn to_markdown(report: &ComplianceReport) -> String {
    let mut md = String::new();

    md.push_str("# Azure Policy Drift Detection Report\n\n");
    md.push_str(&format!(
        "**Scope:** `{}`  \n**Scanned at:** {}  \n**Total resources:** {}  \n**Non-compliant:** {}  \n**Exempt:** {}\n\n",
        report.scope,
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.total_resources,
        report.non_compliant_count,
        report.exempt_count,
    ));

    if report.by_subscription.len() > 1 {
        md.push_str("---\n\n## By Subscription\n\n");
        md.push_str("| Subscription | Resources | Non-Compliant | Exempt |\n|---|---|---|---|\n");
        for sub in &report.by_subscription {
            md.push_str(&format!(
                "| `{}` | {} | {} | {} |\n",
                sub.subscription_id, sub.total_resources, sub.non_compliant_count, sub.exempt_count
            ));
        }
        md.push('\n');
    }

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", report.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", report.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", report.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", report.summary.low_count));
    md.push_str(&format!("| Informational | {} |\n\n", report.summary.informational_count));

    if !report.drifts.is_empty() {
        md.push_str("---\n\n## Drift Findings\n\n");
        for drift in &report.drifts {
            let icon = match drift.severity {
                Severity::Critical => "🔴",
                Severity::High => "🟠",
                Severity::Medium => "🟡",
                Severity::Low => "🔵",
                Severity::Informational => "⚪",
            };
            md.push_str(&format!(
                "### {} `{}` | {} | `{}`\n\n",
                icon, drift.severity, drift.drift_type, drift.resource_name
            ));
            md.push_str(&format!("**Resource:** `{}`  \n", drift.resource_id));
            md.push_str(&format!("**Type:** `{}`  \n", drift.resource_type));
            md.push_str(&format!("**Location:** {}  \n", drift.location));
            md.push_str(&format!("**Policy:** {}  \n\n", drift.policy_name));
            md.push_str(&format!("**Description:** {}  \n\n", drift.description));
            md.push_str(&format!("**Remediation:** {}  \n\n", drift.remediation));
        }
    } else {
        md.push_str("---\n\n**No drift detected.** All scanned resources are compliant.\n\n");
    }

    md.push_str("---\n\n*Generated by Azure Policy Drift Detector. RayStudio*\n");
    md
}

pub fn to_sarif_stub(report: &ComplianceReport) -> String {
    let rules: Vec<serde_json::Value> = report
        .drifts
        .iter()
        .map(|d| {
            serde_json::json!({
                "id": format!("{}", d.drift_type),
                "name": d.policy_name,
                "shortDescription": { "text": d.description },
                "defaultConfiguration": { "level": match d.severity {
                    Severity::Critical | Severity::High => "error",
                    Severity::Medium => "warning",
                    _ => "note",
                }}
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "azure-policy-drift-detector",
                    "version": env!("CARGO_PKG_VERSION"),
                    "rules": rules
                }
            },
            "results": []
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{ComplianceSummary, SubscriptionBreakdown};

    fn make_report(by_subscription: Vec<SubscriptionBreakdown>) -> ComplianceReport {
        ComplianceReport {
            scope: "management-group:mg-test".to_string(),
            scanned_at: chrono::Utc::now(),
            total_resources: 3,
            compliant_count: 1,
            non_compliant_count: 1,
            exempt_count: 1,
            drifts: vec![],
            summary: ComplianceSummary::default(),
            by_subscription,
        }
    }

    #[test]
    fn markdown_shows_breakdown_table_for_multiple_subscriptions() {
        let report = make_report(vec![
            SubscriptionBreakdown { subscription_id: "sub-a".into(), total_resources: 2, non_compliant_count: 1, exempt_count: 0 },
            SubscriptionBreakdown { subscription_id: "sub-b".into(), total_resources: 1, non_compliant_count: 0, exempt_count: 1 },
        ]);
        let md = to_markdown(&report);
        assert!(md.contains("## By Subscription"));
        assert!(md.contains("sub-a"));
        assert!(md.contains("sub-b"));
    }

    #[test]
    fn markdown_omits_breakdown_table_for_a_single_subscription() {
        let report = make_report(vec![SubscriptionBreakdown {
            subscription_id: "sub-a".into(),
            total_resources: 3,
            non_compliant_count: 1,
            exempt_count: 1,
        }]);
        let md = to_markdown(&report);
        assert!(!md.contains("## By Subscription"));
    }

    #[test]
    fn json_export_round_trips_the_scope_field() {
        let report = make_report(vec![]);
        let json = to_json(&report).unwrap();
        assert!(json.contains("\"scope\": \"management-group:mg-test\""));
        let parsed: ComplianceReport = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.scope, "management-group:mg-test");
    }
}
