use anyhow::Result;

use crate::models::{ComplianceReport, Severity};

pub fn to_json(report: &ComplianceReport) -> Result<String> {
    Ok(serde_json::to_string_pretty(report)?)
}

pub fn to_markdown(report: &ComplianceReport) -> String {
    let mut md = String::new();

    md.push_str("# Azure Policy Drift Detection Report\n\n");
    md.push_str(&format!(
        "**Subscription:** `{}`  \n**Scanned at:** {}  \n**Total resources:** {}  \n**Non-compliant:** {}  \n**Exempt:** {}\n\n",
        report.subscription_id,
        report.scanned_at.format("%Y-%m-%d %H:%M UTC"),
        report.total_resources,
        report.non_compliant_count,
        report.exempt_count,
    ));

    md.push_str("---\n\n## Summary\n\n");
    md.push_str("| Severity | Count |\n|---|---|\n");
    md.push_str(&format!("| Critical | {} |\n", report.summary.critical_count));
    md.push_str(&format!("| High | {} |\n", report.summary.high_count));
    md.push_str(&format!("| Medium | {} |\n", report.summary.medium_count));
    md.push_str(&format!("| Low | {} |\n", report.summary.low_count));
    md.push_str(&format!("| Informational | {} |\n\n", report.summary.informational_count));

    if !report.drifts.is_empty() {
        md.push_str("---\n\n## Drift Findings\n\n");
        for drift in &report.drifts {
            let icon = match drift.severity {
                Severity::Critical => "🔴",
                Severity::High => "🟠",
                Severity::Medium => "🟡",
                Severity::Low => "🔵",
                Severity::Informational => "⚪",
            };
            md.push_str(&format!(
                "### {} `{}` | {} | `{}`\n\n",
                icon, drift.severity, drift.drift_type, drift.resource_name
            ));
            md.push_str(&format!("**Resource:** `{}`  \n", drift.resource_id));
            md.push_str(&format!("**Type:** `{}`  \n", drift.resource_type));
            md.push_str(&format!("**Location:** {}  \n", drift.location));
            md.push_str(&format!("**Policy:** {}  \n\n", drift.policy_name));
            md.push_str(&format!("**Description:** {}  \n\n", drift.description));
            md.push_str(&format!("**Remediation:** {}  \n\n", drift.remediation));
        }
    } else {
        md.push_str("---\n\n**No drift detected.** All scanned resources are compliant.\n\n");
    }

    md.push_str("---\n\n*Generated by Azure Policy Drift Detector. RayStudio*\n");
    md
}

pub fn to_sarif_stub(report: &ComplianceReport) -> String {
    let rules: Vec<serde_json::Value> = report
        .drifts
        .iter()
        .map(|d| {
            serde_json::json!({
                "id": format!("{}", d.drift_type),
                "name": d.policy_name,
                "shortDescription": { "text": d.description },
                "defaultConfiguration": { "level": match d.severity {
                    Severity::Critical | Severity::High => "error",
                    Severity::Medium => "warning",
                    _ => "note",
                }}
            })
        })
        .collect();

    let sarif = serde_json::json!({
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {
                "driver": {
                    "name": "azure-policy-drift-detector",
                    "version": "0.1.0",
                    "rules": rules
                }
            },
            "results": []
        }]
    });

    serde_json::to_string_pretty(&sarif).unwrap_or_default()
}
